/**
 * KingsOrder
 */
/**
 * All the app constants comes here
 */


 //*> CONFIGURATIONS
 export const API_TIMEOUT = 30000;

 //*> API CALLING CONSTANTS
export const GET_API = 'GET';
export const POST_API = 'POST';
export const PUT_API = 'PUT';
export const DELETE_API = 'DELETE';
export const UPDATE_API = 'PUT';

//*> APP LOADER
export const START_SPINNER = "START_SPINNER"  
export const STOP_SPINNER = "STOP_SPINNER"

//*> ERROR MODAL
export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL"  
export const HIDE_ERROR_MODAL = "HIDE_ERROR_MODAL"

//*> USER CONSTANTS
export const LOGIN_USER = 'LOGIN_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const SELCT_COUNTRY_FOR_APPOINTMENT = 'SELCT_COUNTRY_FOR_APPOINTMENT';
export const SELECT_LOCATION_FOR_APPOINTMENT = 'SELECT_LOCATION_FOR_APPOINTMENT';
export const GET_PROJECT_LIST_DATA = 'GET_PROJECT_LIST_DATA';
export const GET_PROJECT_DETAIL_DATA = 'GET_PROJECT_DETAIL_DATA';
export const CHANGE_PASSOWRD = 'CHANGE_PASSOWRD';
export const PROJECT_INVENTORY_LIST = 'PROJECT_INVENTORY_LIST';
export const HELP_SUPPORT = 'HELP_SUPPORT';
export const CONTACT_US = 'CONTACT_US';
export const PROJECT_ENQUIRY = 'PROJECT_ENQUIRY';
export const INVENTORY_FLOORPLAN = 'INVENTORY_FLOORPLAN';
export const OOFER_BLOG_LIST = 'OOFER_BLOG_LIST';
export const OOFER_BLOG_DETAIL = 'OOFER_BLOG_DETAIL';
export const CUVERSE_PROJECT = 'CUVERSE_PROJECT';
export const CUVERSE_PROJECT_IMAGE = 'CUVERSE_PROJECT_IMAGE';
